"""routes support pre-shift assignment

Revision ID: d5be1b2deb46
Revises: a84ec2cc7505
Create Date: 2026-08-08 19:24:40.367909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5be1b2deb46'
down_revision: Union[str, None] = 'a84ec2cc7505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: se removió un drop_index espurio de 'uq_customer_single_principal_address'
    # que autogenerate proponía por error — ese índice se creó con SQL crudo en la
    # migración a84ec2cc7505 y no está en el metadata de SQLAlchemy, así que autogenerate
    # cree que "no debería existir". No tocarlo aquí.
    op.add_column('routes', sa.Column('driver_id', sa.UUID(), nullable=False))
    op.add_column('routes', sa.Column('vehicle_id', sa.UUID(), nullable=False))
    op.add_column('routes', sa.Column('fecha', sa.Date(), nullable=False))
    op.alter_column('routes', 'driver_shift_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_routes_driver_id'), 'routes', ['driver_id'], unique=False)
    op.create_index(op.f('ix_routes_fecha'), 'routes', ['fecha'], unique=False)
    op.create_foreign_key(None, 'routes', 'drivers', ['driver_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'routes', 'vehicles', ['vehicle_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_index(op.f('ix_routes_fecha'), table_name='routes')
    op.drop_index(op.f('ix_routes_driver_id'), table_name='routes')
    op.alter_column('routes', 'driver_shift_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('routes', 'fecha')
    op.drop_column('routes', 'vehicle_id')
    op.drop_column('routes', 'driver_id')
    # ### end Alembic commands ###
